#!/usr/bin/env bash
# Write .env.prod (mode 600) with fresh random secrets for docker-compose.prod.yml. Run it ON THE SERVER, once.
#
#   infra/scripts/gen-secrets.sh --domain myhearth.duckdns.org --email you@example.com [--node-ip 203.0.113.7]
#   infra/scripts/gen-secrets.sh            # asks for the domain and email
#   infra/scripts/gen-secrets.sh --force    # replace an existing .env.prod (the old one is kept as .env.prod.bak-<UTC>)
#
# --node-ip: the VM's reserved public IP. Optional but recommended: LiveKit then advertises it directly instead of
# asking a STUN server at every start. Secrets are never printed. .env.prod is gitignored (`.env.*`).
set -euo pipefail
cd "$(dirname "$0")/../.."

out=.env.prod
domain=''
email=''
node_ip=''
force=false

usage() { sed -n '2,8p' "$0" | sed 's/^# \{0,1\}//'; }

while (($# > 0)); do
  case "$1" in
    --domain) domain="${2:-}"; shift 2 ;;
    --domain=*) domain="${1#*=}"; shift ;;
    --email) email="${2:-}"; shift 2 ;;
    --email=*) email="${1#*=}"; shift ;;
    --node-ip) node_ip="${2:-}"; shift 2 ;;
    --node-ip=*) node_ip="${1#*=}"; shift ;;
    --force) force=true; shift ;;
    -h | --help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

command -v openssl >/dev/null || { echo "openssl is required (sudo apt-get install -y openssl)" >&2; exit 1; }

if [[ -e "$out" && "$force" != true ]]; then
  echo "$out already exists; refusing to overwrite it." >&2
  echo "Re-run with --force to replace it. Warning: Postgres keeps the password it was first started with, so a" >&2
  echo "new POSTGRES_PASSWORD breaks an existing database until you change it there too (docs/DEPLOY.md)." >&2
  exit 1
fi

if [[ -z "$domain" ]]; then read -r -p "App domain (e.g. myhearth.duckdns.org): " domain; fi
if [[ -z "$email" ]]; then read -r -p "Email for Let's Encrypt expiry notices: " email; fi
domain="${domain,,}"
domain="${domain#https://}"
domain="${domain%/}"

# A plain hostname: labels of letters, digits and hyphens. LiveKit is served on lk.<domain>.
if ! [[ "$domain" =~ ^([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)*[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$ ]]; then
  echo "Not a valid hostname: '$domain'" >&2
  exit 2
fi
if ! [[ "$email" =~ ^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$ ]]; then
  echo "Not a valid email address: '$email'" >&2
  exit 2
fi

if [[ -n "$node_ip" ]] && ! [[ "$node_ip" =~ ^((25[0-5]|2[0-4][0-9]|1?[0-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1?[0-9]?[0-9])$ ]]; then
  echo "Not an IPv4 address: '$node_ip'" >&2
  exit 2
fi

# Hex only: no characters that need escaping in DATABASE_URL, .env files or YAML. 32 bytes = 256 bits each;
# the LiveKit secret is 64 characters (LiveKit needs >= 32).
postgres_password="$(openssl rand -hex 32)"
livekit_secret="$(openssl rand -hex 32)"
livekit_key=hearth-prod
[[ ${#postgres_password} -eq 64 && ${#livekit_secret} -eq 64 ]] || { echo "openssl rand failed" >&2; exit 1; }

umask 077
tmp="$(mktemp "${out}.tmp.XXXXXX")"
trap 'rm -f "$tmp"' EXIT
cat >"$tmp" <<EOF
# Hearth production environment. Generated by infra/scripts/gen-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Keep this file private (mode 600, never committed). Use it with:
#   docker compose -f docker-compose.prod.yml --env-file .env.prod <command>
# NODE_ENV, COOKIE_SECURE, HEARTH_TEST_MODE, TRUST_PROXY, LIVEKIT_URL and UPLOAD_DIR are fixed in docker-compose.prod.yml.

# --- Domain: app on https://\$HEARTH_DOMAIN, LiveKit on wss://lk.\$HEARTH_DOMAIN ---
HEARTH_DOMAIN=${domain}
ACME_EMAIL=${email}

# --- Postgres (the password only takes effect when the pgdata volume is first created) ---
POSTGRES_USER=hearth
POSTGRES_PASSWORD=${postgres_password}
POSTGRES_DB=hearth

# --- LiveKit (the compose file derives LIVEKIT_KEYS from these two) ---
LIVEKIT_API_KEY=${livekit_key}
LIVEKIT_API_SECRET=${livekit_secret}
# The VM's reserved public IP (optional). Empty = discover it via STUN at every start.
NODE_IP=${node_ip}

# --- Server tunables (defaults from .env.example) ---
LOG_LEVEL=info
SESSION_TTL_DAYS=30
MAX_USERS=25
UPLOAD_GC_INTERVAL_MINUTES=60
UPLOAD_MIN_FREE_MB=2048
VOICE_RECONCILE_MS=60000

# --- Backups (backup sidecar): daily at BACKUP_AT (UTC, HH:MM); keep BACKUP_KEEP nightly backups and
# BACKUP_KEEP_EXTRA of each pre-deploy-*/pre-restore-* kind; refuse a backup below BACKUP_MIN_FREE_MB free ---
BACKUP_AT=03:30
BACKUP_KEEP=7
BACKUP_KEEP_EXTRA=3
BACKUP_MIN_FREE_MB=2048
EOF

if [[ -e "$out" ]]; then
  bak="${out}.bak-$(date -u +%Y%m%dT%H%M%SZ)"
  cp -p "$out" "$bak"
  chmod 600 "$bak"
  echo "Kept the previous file as $bak"
fi
mv "$tmp" "$out"
trap - EXIT
chmod 600 "$out"

# The backup sidecar writes here; keep it private to this user.
mkdir -p data/backups
chmod 700 data/backups

echo "Wrote $out (mode $(stat -c %a "$out")) for https://${domain} and wss://lk.${domain}${node_ip:+ (LiveKit node IP $node_ip)}."
echo "Secrets generated: POSTGRES_PASSWORD, LIVEKIT_API_SECRET (not shown). Next: docs/DEPLOY.md → Build and start."
