import { useEffect, useRef } from 'react';
import { useT } from '../../i18n/useT';
import { onHidden } from '../../lib/capture';
import { sinkIdFor } from '../../lib/voiceSettings';
import { canSelectOutput } from '../../voice/devices';
import { secondaryButton } from '../styles';

const TONE_HZ = 660;
const TONE_SECONDS = 1;
const TONE_GAIN = 0.15;

/**
 * **Play test sound**: a soft one-second tone, generated by an OscillatorNode and played through an
 * `<audio>` element on the chosen output (`setSinkId`), so it is heard where calls will be. A new
 * click restarts it; unmount and tab hide stop it.
 */
export function SpeakerTest({
  outputId,
  onStart,
  onError,
}: {
  outputId: string;
  onStart: () => void;
  onError: (message: string) => void;
}) {
  const t = useT();
  const audioRef = useRef<HTMLAudioElement>(null);
  const stopRef = useRef<(() => void) | null>(null);

  const stop = () => {
    stopRef.current?.();
    stopRef.current = null;
  };

  useEffect(() => {
    const unbind = onHidden(document, () => {
      stopRef.current?.();
      stopRef.current = null;
    });
    return () => {
      unbind();
      stopRef.current?.();
      stopRef.current = null;
    };
  }, []);

  const play = async () => {
    onStart();
    stop();
    const audio = audioRef.current;
    if (audio === null) return;
    let ctx: AudioContext;
    try {
      ctx = new AudioContext();
    } catch {
      onError(t('settings.voice.testSoundFailed'));
      return;
    }
    const oscillator = ctx.createOscillator();
    const gain = ctx.createGain();
    const destination = ctx.createMediaStreamDestination();
    oscillator.type = 'sine';
    oscillator.frequency.value = TONE_HZ;
    oscillator.connect(gain).connect(destination);
    let stopped = false;
    /** Read through a function: a new click, unmount or tab hide may stop it while awaiting. */
    const isStopped = () => stopped;
    let timer: ReturnType<typeof setTimeout> | undefined;
    const cleanup = () => {
      if (stopped) return;
      stopped = true;
      clearTimeout(timer);
      oscillator.disconnect();
      gain.disconnect();
      audio.pause();
      audio.srcObject = null;
      void ctx.close().catch(() => undefined);
    };
    stopRef.current = cleanup;
    try {
      audio.srcObject = destination.stream;
      if (canSelectOutput()) await audio.setSinkId(sinkIdFor(outputId));
      if (isStopped()) return;
      await audio.play();
      if (isStopped()) return;
      // A short fade in and out, so the tone doesn't click.
      const start = ctx.currentTime;
      gain.gain.setValueAtTime(0, start);
      gain.gain.linearRampToValueAtTime(TONE_GAIN, start + 0.05);
      gain.gain.setValueAtTime(TONE_GAIN, start + TONE_SECONDS - 0.15);
      gain.gain.linearRampToValueAtTime(0, start + TONE_SECONDS);
      oscillator.start(start);
      oscillator.stop(start + TONE_SECONDS);
      timer = setTimeout(
        () => {
          cleanup();
          if (stopRef.current === cleanup) stopRef.current = null;
        },
        (TONE_SECONDS + 0.2) * 1000,
      );
    } catch {
      if (isStopped()) return;
      cleanup();
      if (stopRef.current === cleanup) stopRef.current = null;
      onError(t('settings.voice.testSoundFailed'));
    }
  };

  return (
    <div>
      <button
        type="button"
        data-testid="speaker-test"
        className={secondaryButton}
        onClick={() => {
          void play();
        }}
      >
        {t('settings.voice.testSound')}
      </button>
      <audio ref={audioRef} hidden />
    </div>
  );
}
